# Generated by Django 3.0.6 on 2020-05-19 13:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('promotional_price', models.FloatField(blank=True, default=None)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=None, size=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Categories')),
            ],
        ),
    ]
