# Generated by Django 3.0.6 on 2020-05-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photos',
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
