# Generated by Django 3.0.6 on 2020-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200519_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='products/img'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotional_price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
